### ISSUE TITLE
Support for pebble-spring function

### ISSUE THREAD

**Issue by ebussieres** [bjansen/pebble-intellij#10]
It would be awesome to add support for pebble-spring function too.  Complete list of all functions are here http://www.mitchellbosecke.com/pebble/documentation/guide/spring-integration

**Comment by bjansen** [comment]
Do you mean functions like `href()`, `hasErrors()`, `hasFieldErrors()` should be available in the code completion if pebble-spring is configured?

**Comment by ebussieres** [comment]
Yeah exactly

**Comment by bjansen** [comment]
I added autocompletion for declarations coming from pebble-spring, but I'll improve that later with parameter info, and autocompletion of bean names when using the `bean` variable.

**Comment by bjansen** [comment]
I uploaded a snapshot of the next version [here (in the 'Nightly' tab)](https://plugins.jetbrains.com/plugin/9407-pebble/update/38386), for those who'd like to test new features like code completion and navigation.

**Comment by bjansen** [comment]
OK, the plugin will now suggest bean names when autocompleting `beans.xxx`:

![image](https://user-images.githubusercontent.com/281528/30158680-505c722a-93c6-11e7-82b3-e29c50ca685d.png)

It will also show the complete signature for fields and functions added by spring-pebble:

![image](https://user-images.githubusercontent.com/281528/30158800-ab46624a-93c6-11e7-9d37-8c3762ccd508.png)

I believe it's enough for now :)

**Comment by jpolete** [comment]
I'm not getting code completion for spring and spring functions are highlighted as unknown variables. Do I need to do anything specific to enable spring support for the plugin? I have a spring boot / maven project; Intellij 2020.2; Pebble plugin 0.7; Pebble 3.1.4

**Comment by bjansen** [comment]
You need IntelliJ Ultimate, and the Spring facet should be configured correctly I think.

**Comment by jpolete** [comment]
I do have ultimate. Maybe I have something else going on. I'll poke around the spring facet and see if anything looks amiss.

**Comment by bjansen** [comment]
Can you see your Spring beans in the `Spring` tool window?

**Comment by jpolete** [comment]
Can you see your Spring beans in the Spring tool window?

Yes.

**Comment by bjansen** [comment]
OK, I'll look into it later. Thanks for reporting the possible issue.

**Comment by bjansen** [comment]
It works fine on my machine:

> IntelliJ IDEA 2020.2 (Ultimate Edition)
Build #IU-202.6397.94, built on July 27, 2020
Runtime version: 11.0.7+10-b944.20 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 512M
Cores: 12
Non-Bundled Plugins: PsiViewer, com.github.bjansen.intellij.pebble

I'm using the test project located here: https://github.com/bjansen/pebble-intellij/tree/master/pebble-intellij-test

![image](https://user-images.githubusercontent.com/281528/92028200-f10e1a80-ed63-11ea-8964-0a47a057987d.png)

**Comment by bjansen** [comment]
Oh actually it's a bug, the Spring supports only works if either `com.mitchellbosecke.pebble.spring.PebbleView` or `com.mitchellbosecke.pebble.spring4.PebbleView` is in the classpath (an easy way to detect if the project depends on the `pebble-spring` library), but it looks like the latest version is named `com.mitchellbosecke.pebble.spring.servlet.PebbleView`.

Please subscribe to #49 to follow progress.
