### ISSUE TITLE
Pebvariable annotations for arrays don't set the correct type for objects inside the array

### ISSUE THREAD

**Issue by grishka** [bjansen/pebble-intellij#105]
If you write this:
```twig
{# @pebvariable name="results" type="smithereen.data.SearchResult[]" #}
{% for res in results %}
...
{% endfor %}
```
The plugin won't pick up the type of the objects in the array, instead thinking they're `java.lang.Object`s:
![Снимок экрана 2021-07-10 в 13 33 13](https://user-images.githubusercontent.com/1478258/125160232-7df3e280-e184-11eb-90a7-20f5ab0f51d8.png)
Or maybe I'm not specifying arrays/collections correctly, but adding `[]` is the most obvious way so it would make sense to support it if it's not supported.

**Comment by grishka** [comment]
Trying to output a property of an array element produces an even weirder error:
![Снимок экрана 2021-07-10 в 13 45 30](https://user-images.githubusercontent.com/1478258/125160361-1c804380-e185-11eb-9bc2-355511f9ef43.png)

**Comment by bjansen** [comment]
FTR subtypes of `java.lang.Iterable` and `scala.collection.Iterable` are already supported:
<img width="736" alt="image" src="https://github.com/bjansen/pebble-intellij/assets/281528/6ab0b08f-90fe-46db-9e7f-7fe71ec5677a">

I'll throw in support for arrays too.
