### ISSUE TITLE
Redundant PSI children visitor cycle in PebbleHighlightAnnotator

### ISSUE THREAD

**Issue by baylrock** [bjansen/pebble-intellij#123]
Hi!

While playing with plugin sources I probably found a potential place for a small improvement.
I believe plugin performing redundant  PSI children cycle in `com/github/bjansen/intellij/pebble/editor/PebbleHighlightAnnotator.kt` by using `PsiRecursiveElementVisitor`. I believe that `Annotator#annotate` will be called on each tree element (such implementation can be found in some of Intellij plugin sources, like e.g. `properties` language support).

I tried to drop the visitor part locally and it seems to be working all right.

**Comment by bjansen** [comment]
You're right, that visitor is totally unnecessary! I removed it and code is still highlighted as before. 
Our CPUs are grateful to you :)

**Comment by bjansen** [comment]
Fixed in 0e6e5b29
