### ISSUE TITLE
{{map['key']}} error

### ISSUE THREAD

**Issue by sanopl** [bjansen/pebble-intellij#14]
```
{{map['key']}}    {# this shows as error #}
```

**Comment by bjansen** [comment]
I believe this was fixed in version 0.2, that was released a few days ago. Could you try updating the plugin and tell me if the error persists please?

**Comment by sanopl** [comment]
Yes, map/key problem still exists. 

Plugin v0.2 syntax errors:
```
{{ map['key'] }}
{{ underscore_test }}
```

**Comment by bjansen** [comment]
Oh you're right, I thought I fixed that when I migrated the parser to ANTLR4. I'll fix it right away, thanks for reporting the issue!
