### ISSUE TITLE
i18n shows "unknown variable" in IntelliJ

### ISSUE THREAD

**Issue by Schnippsche** [bjansen/pebble-intellij#163]
on every i18n function in *.peb template the gui says 'Unknown variable 'i18n' , but it is a valid function from pebble

![grafik](https://github.com/bjansen/pebble-intellij/assets/49980210/1d2a48fe-9ac6-47c9-95a5-475c1f67b7c5)

**Comment by bjansen** [comment]
Relates to #19

**Comment by bjansen** [comment]
I'm working on autocompletion and references for built-in functions too :)
<img width="657" alt="image" src="https://github.com/bjansen/pebble-intellij/assets/281528/af1657c7-f096-4481-8207-2235e6906f52">
