### ISSUE TITLE
`@pebvariable` without a `name`

### ISSUE THREAD

**Issue by ndawod** [bjansen/pebble-intellij#178]
Hi there, and thanks for this fine piece of software! 🎉

I'm moving away from FreeMarker and during the migration, I noticed that I'm unable to replicate the following behavior from FreeMarker in Pebble:

```freemarker
<#-- @ftlvariable name="" type="com.example.model.DataModel" -->

Hello, ${userName}.
```

In the above example, `userName` is a property defined in the `DataModel` class, which serves as the root data model of the template.

In Pebble, however, one cannot do the following:

```pebble
{# @pebvariable name="" type="com.example.model.DataModel" #}
```

This has no effect on hinting, autocompletion, etc.

Any chance to add support for this in Pebble? The alternative is to define a name, say `name="model"` and then prefix each property with that name:

```pebble
Hello, {{ model.userName }}.
```

Not as elegant...

**Comment by ndawod** [comment]
The context would be the `DataModel` I mentioned earlier, so something like:

```kotlin
data class DataModel(
  val userName: String,
  val userEmail: String,
  val userPhone: PhoneModel,
  // ...
)

data class PhoneModel(
  val code: Int,
  val number: Long
)

val model = DataModel(args)

template.evaluate(writer, model)
```

So, `model` is an instance of a `data class` and not a `Map`.

As you can see, the `model` may indeed contain properties which by themselves are also data models. Or any other type for that matter.

**Comment by bjansen** [comment]
Sorry, I don't understand. `evaluate()` takes a `Map<String, Object>`, how can it work with a data class?

**Comment by ndawod** [comment]
Ohh, darn it... I thought it'd be a plug-and-play to move from FreeMarker (minus the markup refactor, of course). But if `evaluate()` accepts only a Map, then I'll never use Pebble sadly...

Not without a PR though :) So, I wonder, how hard do you think it'd be for a Kotlin developer like me to alter the behavior of `evaluate()` to accept either a Map or `Any`?

**Comment by bjansen** [comment]
I guess it wouldn't be that hard, maybe open an issue at https://github.com/PebbleTemplates/pebble/issues and people there will be able to guide you or tell you if what you're looking for is not possible.

**Comment by ndawod** [comment]
Thanks for your recommendation, I did just that :)
