### ISSUE TITLE
Method invocation with more than one argument not supported

### ISSUE THREAD

**Issue by jansorg** [bjansen/pebble-intellij#22]
In the pebble snippet `{{ context.with("arg1", true) | myFilter }}` the `,` comma after `arg1` is marked as a parsing error. The invocation in Pebble works fine, though.

Thanks for this plugins, it's very helpful!

**Comment by bjansen** [comment]
I think it's because the parser is treating `with` as a keyword (which is only valid in `include` blocks).

**Comment by jansorg** [comment]
@bjansen Thank you for fixing this!
