### ISSUE TITLE
Resolve implicit 'loop' variable

### ISSUE THREAD

**Issue by jansorg** [bjansen/pebble-intellij#26]
Thanks for the variable resolving!
It would be great if the implicit loop variable was resolved, as well.

```
 {% for kwarg in X %}
   { loop.index }}
{% endfor %}
```

**Comment by bjansen** [comment]
Done, I even managed to make the `loop` variable unresolved outside of `for` blocks.

**Comment by jansorg** [comment]
Thanks!
