### ISSUE TITLE
Add support for different file extensions

### ISSUE THREAD

**Issue by pwolaq** [bjansen/pebble-intellij#28]
Hello,

We are using pebble in our project. However, due to different file extensions we are not able to use your plugin, which would be great.

Would it be possible to add support for configurable file extensions? 

Kind regards,
Pawel

**Comment by pwolaq** [comment]
Ok, nevermind, I see that this can be configured via Intellij.

**Comment by mboullouz** [comment]
@pwolaq : how can you configure that using Intellij, can you please share the hint?
Tnx

**Comment by bjansen** [comment]
@mboullouz this can be done in the `File Types` settings, see https://www.jetbrains.com/help/idea/creating-and-registering-file-types.html

**Comment by mboullouz** [comment]
@bjansen thank you man, works great. 
Merci
