### ISSUE TITLE
Missing pebble-intellij file

### ISSUE THREAD

**Issue by pun-ky** [bjansen/pebble-intellij#33]
hey! after clicking "install plugins"

![image](https://user-images.githubusercontent.com/10673561/51459012-624bb600-1d57-11e9-8c2b-d6196fe67195.png)

window displayed with message "Missing pebble-intellij file" (with jar/zip extension; sry don't remember). Then IntelliJ could not start. After launching again, it started but with no plugin installed / again popup displayed about installing "plugins supporting *.peb files found" :(

IntelliJ IDEA 2018.2.7 (Ultimate Edition)
Build #IU-182.5107.41, built on November 26, 2018
JRE: 1.8.0_152-release-1248-b22 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by bjansen** [comment]
Thanks for reporting the problem. Could you try reinstalling the plugin and see if it happens again? If so, I'd need a screenshot of the error message, otherwise I don't think I'll be able to diagnose/fix the problem.

**Comment by pun-ky** [comment]
probably it was an one-timer. now I cannot reproduce it, however installing other plugins never ended with that error so it is rather propable that sth can be improved and is connected with your plugin in my opinion or.... I've got just no luck :) 

greetings
