### ISSUE TITLE
When assigning an array to a variable, brackets are highlighted as an error

### ISSUE THREAD

**Issue by jpolete** [bjansen/pebble-intellij#36]
Love this plugin. Thanks for all your work on it.

When I assign an array to a variable using set, the square brackets are highlighted as a error with an extraneous input error.

> extraneous input '[' expecting {'not', 'null', 'none', '{', '('...

Example: 
```
{%
set actions = [
  {
    'url': '/some-url',
    'icon': 'plus',
    'label': 'New'
  }, 
  {
    'url': '/other-url',
    'icon': 'trash',
    'label': 'delete'
  },
]
%}
```

**Comment by bjansen** [comment]
Hi there, and thanks for the positive feedback! I just fixed the problem, I'll try to make a release tomorrow.

**Comment by jpolete** [comment]
Wow. Awesome. Thank you.
