### ISSUE TITLE
Autocompletion

### ISSUE THREAD

**Issue by bjansen** [bjansen/pebble-intellij#4]
* [x] tags
* [x] block names
* [x] file paths in `extends`/`include` tags

**Comment by leewin12** [comment]
do you have any further progress on this feature?

**Comment by bjansen** [comment]
I'm not using Pebble on my current projects, so this plugin is kinda on hold. However, I have started to work on this issue and I think it will be ready Soon™. For block name completion to be effective, I also have to implement navigation (#6) to also suggest block names declared in imported/extended/included files.
