### ISSUE TITLE
Emmet support

### ISSUE THREAD

**Issue by lulzmachine** [bjansen/pebble-intellij#42]
Hello!

Thanks for the plugin, great work! One thing I would love to have is Emmet support. Being able to get emmet completion of html tags in templates greatly speeds up development

**Comment by bjansen** [comment]
Is your HTML content already highlighted correctly (using the [procedure described in the readme](https://github.com/bjansen/pebble-intellij#mixing-pebble-and-other-languages))?

If so, I would expect the Emmet plugin to work out of the box, unless certain things don't work in template data languages.

**Comment by lulzmachine** [comment]
Thanks! Seems to have done the trick. I would think about maybe adding the word "Emmet" close to the explanation in the readme, for Ctrl+F-compatibility

**Comment by bjansen** [comment]
Done: https://github.com/bjansen/pebble-intellij/commit/f6a0f7882fccb2ef02e64f8bb7679c016cff2e9d
