### ISSUE TITLE
Autocomplete in cascade

### ISSUE THREAD

**Issue by decebals** [bjansen/pebble-intellij#44]
I have following example: 
![image](https://user-images.githubusercontent.com/1248311/86634028-0ec83900-bfda-11ea-97cd-bc5c90198e35.png)

I can use autocomplete for ticket (`ticket.subject`) but the autocomplete for embedded types doesn't work (`ticket.client.name`)

**Comment by bjansen** [comment]
Could you please try this build and let me know if it fixes the problem?

[pebble-intellij.zip](https://github.com/bjansen/pebble-intellij/files/4893114/pebble-intellij.zip)

**Comment by bjansen** [comment]
By the way you don't need to declare `@pebvariable`s for `ticket`, `client` etc. Only one should be needed for `tickets`, the others should be inferred automatically.

**Comment by decebals** [comment]
> Could you please try this build and let me know if it fixes the problem?

I don't see any improvement.
I downloaded the zip supplied by you in the comment and I updated 
`/home/decebal/.IntelliJIdea2019.3/config/plugins/pebble-intellij/lib` with the content of zip. Do I have to do anything else?

**Comment by bjansen** [comment]
Please follow this procedure to install a plugin from disk instead: https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk

**Comment by decebals** [comment]
> Please follow this procedure to install a plugin from disk instead

Thanks for information.

I confirm that it's work as expected. Thank you!
