### ISSUE TITLE
Fields from superclasses are not recognized, reported as nonexistent

### ISSUE THREAD

**Issue by grishka** [bjansen/pebble-intellij#45]
A screenshot worth a thousand words:
![Снимок экрана 2020-07-22 в 16 28 17](https://user-images.githubusercontent.com/1478258/88182105-74eac800-cc38-11ea-90a7-58634666f4dd.png)
Note that the fields that are declared in the `Post` class itself (`id`, `user`) and getter methods (`getInternalURL()`) are considered valid.

Classes are declared as follows:
```java
public class ActivityPubObject{
    // ...
    public Date published;
    // ...
}
```
```java
public class Post extends ActivityPubObject{
    // ... additional fields ...
}
```

**Comment by bjansen** [comment]
Good catch, thanks for reporting the problem!
