### ISSUE TITLE
Pebvariable does not work

### ISSUE THREAD

**Issue by objectProgrammer** [bjansen/pebble-intellij#53]
It only works with JDK classes, I cannot use my own classes. I'm using Gradle. There is no autocompletion when I write the qualified name of my classes and it just draws a red line under the attribute of the variable.

**Comment by bjansen** [comment]
This should work, I'll look into it. Thanks for reporting the problem.

**Comment by bjansen** [comment]
Does code completion work when you hit <kbd>ctrl</kbd>-<kbd>space</kbd> twice?

Both completion and navigation work fine in a sample Maven project, I'm surprised it doesn't work with Gradle.

**Comment by bjansen** [comment]
Also, are your classes written in Java, or some other JVM language?

**Comment by objectProgrammer** [comment]
> Does code completion work when you hit ctrl-space twice?

No.

> Also, are your classes written in Java, or some other JVM language?

100% Java

**Comment by bjansen** [comment]
With plugin v0.9, autocompletion works fine in the `pebble-intellij` project itself, which is Gradle+Kotlin:

https://user-images.githubusercontent.com/281528/107562372-06735480-6be0-11eb-9220-beff0552b661.mov

Is it still failing to work in your IDE?

**Comment by bjansen** [comment]
Oh OK I see, it only works when you don't specify any package. It doesn't autocomplete anything after `com.github.bjansen.` for example.

**Comment by bjansen** [comment]
What I'm observing:
* completion works fine for `.peb` files that are in a source root (like `src/main/resources`)
* completion does not work for `.peb` files that are outside a source root

It makes sense to me because how would the plugin know which classes to auto-complete outside of source roots?

**Comment by bjansen** [comment]
@objectProgrammer are your .peb files under a source root?

**Comment by objectProgrammer** [comment]
No, my peb files are in the `Project/folder`, the code is in `Project/src/main/java/...` is this incorrect?

**Comment by objectProgrammer** [comment]
It works! Sorry for the confusion, maybe it should be noted in README?

**Comment by objectProgrammer** [comment]
Package and class autocompletion works as well :)

**Comment by bjansen** [comment]
Yep, I think it boils down to a wrong 'scope' that didn't include your own source files (in this scenario, code completion is delegated to a feature that already exists in IntelliJ, so I don't have the exact details on how it works).

**Comment by bjansen** [comment]
I updated the readme.

BTW, have you tried the build provided here? https://github.com/bjansen/pebble-intellij/issues/74#issuecomment-777833331 It should fix a lot of bugs that you've encountered.

**Comment by objectProgrammer** [comment]
Thanks!

**Comment by objectProgrammer** [comment]
@bjansen In the second image of the readme, the templates folder is in the project root, not in the src folder. That could perhaps cause confusion?
