### ISSUE TITLE
Syntax error with operators and filters

### ISSUE THREAD

**Issue by rockidude** [bjansen/pebble-intellij#55]
The Pebble Intellij Plugin shows a syntax error for valid Pebble code if you use a combination of operators and filters.

Syntax error examples:

![grafik](https://user-images.githubusercontent.com/12084766/99657230-31755e80-2a5e-11eb-877c-27731c483c70.png)

![grafik](https://user-images.githubusercontent.com/12084766/99657369-5d90df80-2a5e-11eb-9897-2f997460426a.png)

If just using an operator or a filter, it works.

![grafik](https://user-images.githubusercontent.com/12084766/99657498-844f1600-2a5e-11eb-8d70-b2d1a402d3f7.png)

![grafik](https://user-images.githubusercontent.com/12084766/99657554-95982280-2a5e-11eb-8e07-ce801955e386.png)

**Comment by objectProgrammer** [comment]
Simpler ones like `{{ ("aaa" | upper) }}` cause syntax error as well.

**Comment by bjansen** [comment]
This is fixed, thanks!

**Comment by bjansen** [comment]
Quick question though: are `~+` and `++` custom operators? They are currently parsed as `~` (contact) `+` (positive sign) and `+` (addition) `+` (positive sign), but I guess that's probably wrong. 

FYI custom operators are (currently) not supported by the parser, so in other cases it could still result in parsing errors (for example if the operator was `$`, `@`, `&` etc.).

**Comment by rockidude** [comment]
Thanks! Yes, these are custom operators.
