### ISSUE TITLE
recognize .pebble files, and customize recognized extensions

### ISSUE THREAD

**Issue by xenoterracide** [bjansen/pebble-intellij#56]
see https://github.com/PebbleTemplates/pebble/issues/553 `.pebble` is the default for spring, I'm not using spring, but I'm using pebble for scaffolding, with files such as java templates. Since the extension is customizable, it makes sense to allow a list of file extensions as well (since you may have more than one engine active).

Lastly like SQL in Intellij IDEA ultimate, if it's not possible yet, allow highlighting of pebble in strings in a given file extension (for tests and such), I think this could/should be configurable per file, or maybe from a root path (my entire project doesn't use pebble). If you want I can make another ticket for this, but since I'm not certain if it's already possible I haven't.

**Comment by bjansen** [comment]
Most of the tests and documentation in https://github.com/PebbleTemplates/pebble use the `.peb` extension, which is also the default in this plugin. You can already registers other extensions to be recognized as Pebble templates in `Preferences | Editor | File Types`.

> allow highlighting of pebble in strings in a given file extension 

Not sure I understand your use case. The only case I'm aware of is `com.mitchellbosecke.pebble.loader.StringLoader` which loads templates from hard-coded strings instead of external files. Is this what you are talking about?

**Comment by xenoterracide** [comment]
>  which loads templates from hard-coded strings instead of external files. Is this what you are talking about?

yes

> use the .peb

hmm... then it's unfortunate that spring uses .pebble, still might be good to support it out of the box

**Comment by bjansen** [comment]
You might be looking for language injection, which I just tested on [a random test class in the Pebble repo](https://github.com/PebbleTemplates/pebble/blob/2634c1c7c1664e1b4d946bcc463cd1ca84d5f252/pebble/src/test/java/com/mitchellbosecke/pebble/ContextTest.java).

Put your cursor on the String argument passed to `getTemplate()`, for example `pebble.getTemplate("{{ foo }}")`, then press <kbd>Alt</kbd>-<kbd>Enter</kbd>, select `Inject language or reference`, then select `Pebble`.

This can be modified later on in `Preferences | Editor | Language Injections`.

**Comment by xenoterracide** [comment]
since pebble doesn't document .peb which I'm arguing for documenting a standard file extension in that upstream ticket. It might be good to document it somewhere visible in the plugin itself. Outside of this and supporting `.pebble` out of the box, which is up to you, you can close this ticket.

**Comment by bjansen** [comment]
I can definitely pre-configure the missing extension + language injection in `StringLoader`, sure. Thanks for your feedback!
