### ISSUE TITLE
Escaping quote does not work

### ISSUE THREAD

**Issue by objectProgrammer** [bjansen/pebble-intellij#59]
`{{ "And he said \"Hello\"" }}` --> `And he said "Hello"` is perfectly fine pebble syntax but the plugin ignores the backslash and ends the string at the first quote ("He) so the rest becomes a syntax error.

**Comment by objectProgrammer** [comment]
Sorry, I'm going to be a little annoying now..

What happens if I do `{{ "test\\" }}`? Pebble outputs `test\`. (And also, single quotes?)

**Comment by bjansen** [comment]
I guess `{{ "test\\" }}` leads to an unclosed string in the IDE. 
Single quotes were not fixed, so they suffer from the same bugs.

**Comment by bjansen** [comment]
I think I got it right this time, based on the regex and unit tests used in Pebble:

![image](https://user-images.githubusercontent.com/281528/107851552-29358100-6e0b-11eb-9f64-1974504b9b87.png)

**Comment by objectProgrammer** [comment]
Thank you for your efforts
