### ISSUE TITLE
Methods and fields on literals are syntax errors

### ISSUE THREAD

**Issue by objectProgrammer** [bjansen/pebble-intellij#62]
`{{ "hello".toUpperCase() }}` is considered a syntax error.

Well, perhaps fields should be considered errors because I don't know any literal that has fields.

**Comment by bjansen** [comment]
>I don't know any literal that has fields.

Well, Pebbled treats things like `isEmpty()` as an `empty` field, so the parser should also accept `"".empty`.

**Comment by bjansen** [comment]
Looking good :)

<img width="454" src="https://user-images.githubusercontent.com/281528/108596838-d8cc9f00-7387-11eb-8632-91f30795cbff.png"/>

**Comment by objectProgrammer** [comment]
Though I have disabled that in my resolver :)
