### ISSUE TITLE
New identifier pattern

### ISSUE THREAD

**Issue by objectProgrammer** [bjansen/pebble-intellij#63]
Soon my pull request at https://github.com/PebbleTemplates/pebble/pull/544 will be merged so the identifier regex will need to be changed to `[\\p{IsLetter}_][\\p{IsLetter}\\p{IsDigit}_]*`. I hope that `\\p{...}` is usable in ANTLR.

**Comment by bjansen** [comment]
Yep, ANTLR supports Unicode properties: https://github.com/antlr/antlr4/blob/master/doc/lexer-rules.md#lexer-rule-elements

Thanks for the PR, I'll wait for your PR on PebbleTemplates/pebble to be merged before merging this one.

**Comment by objectProgrammer** [comment]
Finally, no more 50 syntax errors per file :)

**Comment by objectProgrammer** [comment]
@bjansen It is merged now
