### ISSUE TITLE
| character in parantheses causes syntax error

### ISSUE THREAD

**Issue by objectProgrammer** [bjansen/pebble-intellij#65]
`{{ ("aaa" + ("b" | upper)) | capitalize }}` = syntax error.

**Comment by objectProgrammer** [comment]
Oh, #55 already exists.

**Comment by bjansen** [comment]
It's fixed, pipes were only supported at the end of the parent expression, now they can also appear in the middle.

**Comment by objectProgrammer** [comment]
Thank you for your effort!
