### ISSUE TITLE
exception: child block end is after parent block end

### ISSUE THREAD

**Issue by schmeic** [bjansen/pebble-intellij#69]
I'm getting this exception in the IDE:
`child block end is after parent block end in #Pebble #formatter`
and this exception is "induced":
`some block intersects with whitespace in #Pebble #formatter`

But the template renders fine, and all the blocks look ok. How can I figure out where exactly in the file is causing this exception?
Also, would it be possible to just show this in the editor rather than throwing an exception?

**Comment by bjansen** [comment]
The problem looks very similar to https://github.com/bjansen/pebble-intellij/issues/58#issuecomment-743755461.
It's a bug in the plugin, not a parser error, so it should not be shown in the editor.

**Comment by schmeic** [comment]
Yes, it does seem like it's the same as #58 (sorry, should have found that). I've subscribed to #58, please let me know if there is anything I can do to help test.

**Comment by schmeic** [comment]
When do you plan on releasing 0.9? Or is there another way I can try out the fix?

**Comment by bjansen** [comment]
Probably in a couple of days, I still want to fix a few other things. Meanwhile, you can use a snapshot build: https://github.com/bjansen/pebble-intellij/issues/74#issuecomment-777833331

Installation instructions here: https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk
