### ISSUE TITLE
Code completion

### ISSUE THREAD

**Issue by gringofe** [bjansen/pebble-intellij#70]
Hello,

I just tried [code completion](https://github.com/bjansen/pebble-intellij#using-code-completion) but it doesn't output anything to the webpage. Is there anything I'm missing? (Great plugin otherwise btw)

**Comment by bjansen** [comment]
Hi,

Could you post an example where code completion does not work please?

**Comment by gringofe** [comment]
Just did the same thing as in the readme (can't disclose my sourcecode). Does it matter that i'm using Kotlin?

**Comment by bjansen** [comment]
Ah yes it matters, at the moment only Java classes are supported. I'll have to see if there's a generic way to query IntelliJ's index to list declarations in other JVM languages.

**Comment by gringofe** [comment]
Okay, thanks for the info, I'll use java interfaces then.

**Comment by bjansen** [comment]
OK I stand corrected, Kotlin classes work fine in a sample Maven project.

Kotlin code:
<img width="361" alt="image" src="https://user-images.githubusercontent.com/281528/102820645-e55b6800-43d5-11eb-8e62-cf93cf38fe3c.png">

Pebble template:
<img width="542" alt="image" src="https://user-images.githubusercontent.com/281528/102820585-cc52b700-43d5-11eb-8b27-06e59480f643.png">

I haven't tested with Kotlin code compiled to JAR libs, but I expect it to work as well.

**Comment by bjansen** [comment]
As usual, completion works if you use a `@pebvariable` hint to let the plugin know what type `inst` is in the example above. 

Could you try this and let me know how it works?

**Comment by gringofe** [comment]
I just tested a few things and it turns out that autocompletion does not work if you are trying to use it in a block from a parent template. 

For example, my parent template contains the navbar and footer, and there is a div containing ` {% block content %}{% endblock %}`. I extend that template using `{% extends "base-template.peb" %}` and add 
```
{% block content %}

{% endblock %}
``` 
in which I add my content. When I try to use autocomplete there, it does not work, and it doesn't event render in the browser. If I use it outside of the block, it works just fine.

**Comment by bjansen** [comment]
> When I try to use autocomplete there, it does not work

You mean in your _child_ template you try auto-completing members of a `@pebvariable` declared in the _parent_ template?
