### ISSUE TITLE
Backspace key at the beginning of the line does nothing

### ISSUE THREAD

**Issue by grishka** [bjansen/pebble-intellij#75]
As the title says. I have IdeaVim installed, but disabling it didn't make a difference. It does erase tab characters and line breaks in Java files.

Possibly related: if I have IdeaVim enabled, pressing `o` to create a new line after the current one and then `{` makes the cursor jump to the beginning of the file. Putting it back with on that empty line using mouse and pressing `{` again types `{`. Exiting out of insert mode and doing this again makes it jump to the beginning again.

**Comment by grishka** [comment]
Oh, I see, this is a duplicate of #58. I'm leaving this for the IdeaVim part then.

**Comment by bjansen** [comment]
`{` is Vim's default shortcut to go to the beginning of the file, right? Do you have the same problem in other (non-Pebble) file types?

**Comment by grishka** [comment]
It goes to the beginning of the paragraph, but no. It's only in Pebble templates. It does act as if you pressed `{` in normal mode except it happens in insert mode.

Feels like maybe you're doing something too low-level with keyboard events?

**Comment by bjansen** [comment]
Seems like I can also close this one, according to your comment (https://github.com/bjansen/pebble-intellij/issues/74#issuecomment-777835864).
