### ISSUE TITLE
Pebble "empty" keyword flagged as "Unknown variable"

### ISSUE THREAD

**Issue by jpolete** [bjansen/pebble-intellij#88]
The Pebble keyword "empty" is highlighted as an unknown variable. For example in this snippet IntelliJ will hightlight empty with the message "Unknown variable 'empty'". 

```
{% if user.email is empty %}
	...
{% endif %}
```
Would be great if the plugin could recognize empty as a keyword and not flag it.

https://pebbletemplates.io/wiki/test/empty/ 

Thanks.

**Comment by bjansen** [comment]
This was actually implemented in #51
